package iti.android.wheatherappjetpackcompose.dataLayer.repository

import iti.android.wheatherappjetpackcompose.dataLayer.source.local.ILocalDataSource
import iti.android.wheatherappjetpackcompose.dataLayer.source.remote.IRemoteDataSource

interface RepositoryInterface : ILocalDataSource, IRemoteDataSource