package iti.android.wheatherappjetpackcompose.domainLayer.usecase.favorite

import iti.android.wheatherappjetpackcompose.domainLayer.repository.IFavoriteRepository

class DeleteFavoriteUseCase(private val repository: IFavoriteRepository)