package iti.android.wheatherappjetpackcompose.domainLayer.usecase.favorite

import iti.android.wheatherappjetpackcompose.domainLayer.repository.IFavoriteRepository

class GetFavoritesUseCase(private val repository: IFavoriteRepository)